name: Build nvidia 550 amd64 (dev)

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pika-package-container:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3

    - name: Update apt cache
      run: apt-get update -y
    
    - name: Build Package
      run: ./amd64-550-main.sh
        
