name: Build nvidia 550 i386 (dev)

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/pikaos-linux/pika-i386-package-container:latest
      volumes:
        - /proc:/proc
      options: --privileged -it

    steps:
    - uses: actions/checkout@v3
    
    - name: Update apt cache
      run: apt-get update -y
    
    - name: Build Package
      run: ./i386-550-main.sh

        
